name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/icad_tone_detection

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Upgrade pip & install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build only a wheel from pyproject.toml
        run: |
          # By default, "python -m build" creates both wheel + sdist.
          # You can limit to just wheel with --wheel:
          python -m build

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
