name: Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  # ------------------------------------------------------------------
  # 1) Build wheels for each (platform, python-version)
  # ------------------------------------------------------------------
  build:
    # Instead of pick_runner, we define a matrix with both 'platform' and 'os'
    strategy:
      fail-fast: false
      matrix:
        include:
          # 5 platforms with a mapped 'os':
          - platform: linux_x86_64
            os: ubuntu-latest
          - platform: linux_arm64
            os: ubuntu-latest
          - platform: windows_x86_64
            os: windows-latest
          - platform: macos_x86_64
            os: macos-latest
          - platform: macos_arm64
            os: macos-latest

        # Now also vary the python version
        python-version: ["3.10", "3.11", "3.12"]

      # That yields 15 builds (5 platforms × 3 py versions)

    # This sets the runner from the matrix 'os' key
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "::set-output name=version::$VERSION"

      - name: Prune extra binaries
        run: |
          # Remove bin folders that don't match `matrix.platform`
          # e.g. if platform=linux_x86_64, remove windows_* / macos_* / linux_arm64, etc.
          if [[ "${{ matrix.platform }}" == linux_* ]]; then
            rm -rf src/icad_tone_detection/bin/macos_* src/icad_tone_detection/bin/windows_* || true
            if [[ "${{ matrix.platform }}" == "linux_x86_64" ]]; then
              rm -rf src/icad_tone_detection/bin/linux_arm64 || true
            else
              rm -rf src/icad_tone_detection/bin/linux_x86_64 || true
            fi
          elif [[ "${{ matrix.platform }}" == windows_* ]]; then
            rm -rf src/icad_tone_detection/bin/linux_* src/icad_tone_detection/bin/macos_* || true
          elif [[ "${{ matrix.platform }}" == macos_* ]]; then
            rm -rf src/icad_tone_detection/bin/windows_* src/icad_tone_detection/bin/linux_* || true
            if [[ "${{ matrix.platform }}" == "macos_x86_64" ]]; then
              rm -rf src/icad_tone_detection/bin/macos_arm64 || true
            else
              rm -rf src/icad_tone_detection/bin/macos_x86_64 || true
            fi
          fi
          find src/icad_tone_detection/bin -type f ! -name '*.exe' -exec chmod +x {} \; 2>/dev/null || true

      - name: Build distributions (wheel + sdist)
        run: python -m build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.platform }}-py${{ matrix.python-version }}
          path: dist/*

      - name: Publish package via Trusted Publisher
        if: ${{ github.ref == 'refs/heads/main' && (matrix.python-version == '3.10' || matrix.python-version == '3.11' || matrix.python-version == '3.12') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          environment: pypi

  # ------------------------------------------------------------------
  # 2) Create a separate GitHub Release per OS/arch
  # ------------------------------------------------------------------
  release:
    needs: build

    # Same approach: define 'platform' + 'os' in the matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux_x86_64
            os: ubuntu-latest
          - platform: linux_arm64
            os: ubuntu-latest
          - platform: windows_x86_64
            os: windows-latest
          - platform: macos_x86_64
            os: macos-latest
          - platform: macos_arm64
            os: macos-latest

    runs-on: ${{ matrix.os }}

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Get version from build
        run: |
          echo "VERSION=${{ needs.build.outputs.version }}" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          # Grab all python versions for this platform
          name: dist-${{ matrix.platform }}-py**
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}-${{ matrix.platform }}
          name: Release v${{ env.VERSION }} for ${{ matrix.platform }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
